version: '3'

services:
  mysql:
    image: mysql
    environment:
    - MYSQL_ROOT_PASSWORD=admin
    - MYSQL_DATABASE=admin
    - MYSQL_USER=admin
    - MYSQL_PASSWORD=admin
    ports:
      - "3306:3306"
    networks:
      - network-mercafacil

  postgresql:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "admin"
      POSTGRES_USER: "admin"
      POSTGRES_DB: admin
    networks:
      - network-mercafacil

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - 3333:3333
    volumes:
      - .:/home/node/app
    networks:
      - network-mercafacil
    depends_on:
      - mysql
      - postgresql

networks:
  network-mercafacil:
    driver: bridge
